POST http://localhost:5000/api/registerMentor
Content-Type: application/json

{
    "name": "west",
    "email": "west@gmail.com",
    "password": "west"
}

###
POST http://localhost:5000/api/registerStudent
Content-Type: application/json

{
    "name": "june", 
    "email": "june@gmail.com",
    "password": "june"
}

### 
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "sheila@gmail.com",
    "password": "sheila"
}


###
POST http://localhost:5000/api/assessments
Content-Type: application/json

{
    "title": "Ass12",
    "description": "This is a test assessment 13",
    "mentorId": 1
}

###
POST http://localhost:5000/api/questions/1/12
Content-Type: application/json

{
  "questions": [
    {
      "title": "Question 1",
      "choice1": "Opt A",
      "choice2": "Opt B",
      "choice3": "Opt C",
      "choice4": "Opt D",
      "correctChoice": "Opt A"
    },
    {
      "title": "Question 2",
      "choice1": "Opt X",
      "choice2": "Opt Y",
      "choice3": "Opt Z",
      "choice4": "Opt W",
      "correctChoice": "Opt Y"
    }
  ]
}

###
POST http://localhost:5000/api/answers
Content-Type: application/json

{
    "studentId": 1,
    "assessmentId": 2,
    "answers": ["Opt A", "Opt B", "Opt A", "Opt D" ]
}

### 
POST http://localhost:5000/api/sendInvite
Content-Type: application/json

{
    "mentorId": "1",  
    "studentIds": ["1", "15"],  
    "assessmentId": "12"  
}


###
GET http://localhost:5000/api/notifications/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInJvbGUiOiJzdHVkZW50IiwiaWF0IjoxNzA4MjQxMTMyLCJleHAiOjE3MDgyNDQ3MzJ9.cHGL21XPaEdvNw8oNQ8ctg-ta17Vnhm1_GwuKhm7iJg

###
POST http://localhost:5000/api/acceptInvitation/2
Content-Type: application/json

{
    "response": "decline"
}

###
GET http://localhost:5000/api/student/1
Content-Type:  application/json

###
GET http://localhost:5000/api/questions/2
Content-Type: application/json

###
GET http://localhost:5000/api/grades/1
Content-Type: application/json

###
GET http://localhost:5000/api/students
Content-Type: application/json

###
GET http://localhost:5000/api/assessments/1
Content-Type: application/json

###
GET http://localhost:5000/api/allgrades/1
Content-Type: application/json


