POST http://localhost:5000/api/registerMentor
Content-Type: application/json

{
    "name": "west",
    "email": "west@gmail.com",
    "password": "west"
}

###
GET http://localhost:5000/api

###
POST http://localhost:5000/api/registerStudent
Content-Type: application/json

{
    "name": "sheila", 
    "email": "sheila@gmail.com",
    "password": "sheila"
}

###
POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "sheila@gmail.com",
    "password": "sheila"
}


###
POST http://localhost:5000/api/assessments
Content-Type: application/json

{
    "title": "Ass1",
    "description": "This is a test assessment",
    "mentorId": 1
}

###
POST http://localhost:5000/api/questions/1/1
Content-Type: application/json

{
    "title": "Question 1",
    "choice1": "Opt A",
    "choice2": "Opt B",
    "choice3": "Opt C",
    "choice4": "Opt D",
    "correctChoice": "Option A"

}

###

